// Phone-case model lists, shared between the client (CaseCustomizer dropdown)
// and the server (cart checkout validation). They live here instead of in
// Stripe product metadata because Stripe caps each metadata value at 500
// characters and the Samsung list alone is far longer. Products only carry a
// short `caseType` flag ("iphone" | "samsung"); the actual model list is
// resolved from this map by both sides.

export const IPHONE_MODELS: string[] = [
  "iPhone 7",
  "iPhone 7 Plus",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone X",
  "iPhone XR",
  "iPhone XS",
  "iPhone XS Max",
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max",
  "iPhone 12 mini",
  "iPhone 12",
  "iPhone 12 Pro",
  "iPhone 12 Pro Max",
  "iPhone 13 mini",
  "iPhone 13",
  "iPhone 13 Pro",
  "iPhone 13 Pro Max",
  "iPhone 14",
  "iPhone 14 Plus",
  "iPhone 14 Pro",
  "iPhone 14 Pro Max",
  "iPhone 15",
  "iPhone 15 Plus",
  "iPhone 15 Pro",
  "iPhone 15 Pro Max",
  "iPhone 16",
  "iPhone 16 Plus",
  "iPhone 16 Pro",
  "iPhone 16 Pro Max",
  "iPhone 17",
  "iPhone 17 Air",
  "iPhone 17 Pro",
  "iPhone 17 Pro Max",
];

export const SAMSUNG_MODELS: string[] = [
  // Galaxy S series
  "Galaxy S7",
  "Galaxy S7 Edge",
  "Galaxy S8",
  "Galaxy S8+",
  "Galaxy S9",
  "Galaxy S9+",
  "Galaxy S10e",
  "Galaxy S10",
  "Galaxy S10+",
  "Galaxy S20",
  "Galaxy S20+",
  "Galaxy S20 Ultra",
  "Galaxy S20 FE",
  "Galaxy S21",
  "Galaxy S21+",
  "Galaxy S21 Ultra",
  "Galaxy S21 FE",
  "Galaxy S22",
  "Galaxy S22+",
  "Galaxy S22 Ultra",
  "Galaxy S23",
  "Galaxy S23+",
  "Galaxy S23 Ultra",
  "Galaxy S23 FE",
  "Galaxy S24",
  "Galaxy S24+",
  "Galaxy S24 Ultra",
  "Galaxy S24 FE",
  "Galaxy S25",
  "Galaxy S25+",
  "Galaxy S25 Ultra",
  // Galaxy A series
  "Galaxy A10",
  "Galaxy A11",
  "Galaxy A12",
  "Galaxy A13",
  "Galaxy A14",
  "Galaxy A15",
  "Galaxy A16",
  "Galaxy A20",
  "Galaxy A21",
  "Galaxy A21s",
  "Galaxy A22",
  "Galaxy A23",
  "Galaxy A24",
  "Galaxy A25",
  "Galaxy A30",
  "Galaxy A31",
  "Galaxy A32",
  "Galaxy A33",
  "Galaxy A34",
  "Galaxy A35",
  "Galaxy A36",
  "Galaxy A50",
  "Galaxy A51",
  "Galaxy A52",
  "Galaxy A53",
  "Galaxy A54",
  "Galaxy A55",
  "Galaxy A70",
  "Galaxy A71",
  "Galaxy A72",
  "Galaxy A73",
];

export const PHONE_MODELS_BY_TYPE: Record<string, string[]> = {
  iphone: IPHONE_MODELS,
  samsung: SAMSUNG_MODELS,
};

export const PHONE_MODEL_LABEL: Record<string, string> = {
  iphone: "iPhone Model",
  samsung: "Samsung Model",
};
